INSERT INTO m_super_rare(id, name, pronunciation) VALUES(1,'–¾“ú‚É‚ÍÁ‚¦‚é','‚ ‚·‚É‚Í‚«‚¦‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(2,'‚ ‚è‚¦‚È‚¢','‚ ‚è‚¦‚È‚¢'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(3,'å‚ğ‹\‚­','‚µ‚ã‚ğ‚ ‚´‚Ş‚­'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(4,'å‚ğ“±‚­','‚µ‚ã‚ğ‚İ‚¿‚Ñ‚­'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(5,'‘§‚ª~‚Ü‚é','‚¢‚«‚ª‚Æ‚Ü‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(6,'Î‚É‚ß‚è‚Ş','‚¢‚µ‚É‚ß‚è‚±‚Ş'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(7,'ˆÙŸŒ³‚É‚ ‚é','‚¢‚¶‚°‚ñ‚É‚ ‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(8,'‚¢‚¸‚ê’D‚í‚ê‚é','‚¢‚¸‚ê‚¤‚Î‚í‚ê‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(9,'ƒEƒTƒM‚ÉŠš‚Ü‚ê‚é','‚¤‚³‚¬‚É‚©‚Ü‚ê‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(10,'‰i‹v‚È‚é','‚¦‚¢‚«‚ã‚¤‚È‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(11,'‘I‚Î‚ê‚µ','‚¦‚ç‚Î‚ê‚µ'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(12,'—‚Æ‚µ•¨‚Ì','‚¨‚Æ‚µ‚à‚Ì‚Ì'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(13,'I‚í‚ç‚È‚¢','‚¨‚í‚ç‚È‚¢'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(14,'Ÿè‚É“®‚­','‚©‚Á‚Ä‚É‚¤‚²‚­'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(15,'_‚Ì••‚¶‚½','‚©‚İ‚Ì‚Ó‚¤‚¶‚½'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(16,'Š½Šì‚ğŒÄ‚Ô','‚©‚ñ‚«‚ğ‚æ‚Ô'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(17,'ŠïÕ“I‚È','‚«‚¹‚«‚Ä‚«‚È'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(18,'‹U‘•‚³‚ê‚µ','‚¬‚»‚¤‚³‚ê‚µ'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(19,'–k‚ğŒü‚­','‚«‚½‚ğ‚Ş‚­'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(20,'K‰^‚ğŒÄ‚Ô','‚±‚¤‚¤‚ñ‚ğ‚æ‚Ô'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(21,'œ’›‚È‚é','‚±‚¤‚±‚Â‚È‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(22,'K•Ÿ‚È‚é','‚±‚¤‚¤‚ñ‚È‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(23,'‹•‹ó‚©‚çŒ»‚ê‚µ','‚±‚­‚¤‚©‚ç‚ ‚ç‚í‚ê‚µ'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(24,'Œ‚ÅŒê‚é','‚±‚Ô‚µ‚Å‚©‚½‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(25,'ÅŒã‚Ì','‚³‚¢‚²‚Ì'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(26,'Å‰‚Ì','‚³‚¢‚µ‚å‚Ì'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(27,'‹t‚ç‚¢‘±‚¯‚é','‚³‚©‚ç‚¢‚Â‚Ã‚¯‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(28,'æ‚ğs‚­','‚³‚«‚ğ‚¢‚­'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(29,'c‘œ‚ªc‚é','‚´‚ñ‚¼‚¤‚ª‚Ì‚±‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(30,'€Šú‚Éè‚É“ü‚é','‚µ‚«‚É‚Ä‚É‚Í‚¢‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(31,'‹ó‚ğ’´‚¦‚é','‚¶‚­‚¤‚ğ‚±‚¦‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(32,'¿—Ê‚ª‚¨‚©‚µ‚¢','‚µ‚Â‚è‚å‚¤‚ª‚¨‚©‚µ‚¢'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(33,'©–‚µ‚½‚¢','‚¶‚Ü‚ñ‚µ‚½‚¢'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(34,'ål‚æ‚èŒ«‚¢','‚µ‚ã‚¶‚ñ‚æ‚è‚©‚µ‚±‚¢'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(35,'’m‚ç‚ê‚´‚é','‚µ‚ç‚ê‚´‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(36,'^À‚ğ’m‚é','‚µ‚ñ‚¶‚Â‚ğ‚µ‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(37,'“§‚«’Ê‚é','‚·‚«‚Æ‚¨‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(38,'‘S‚Ä‚ªŒ©‚¦‚é','‚·‚×‚Ä‚ª‚İ‚¦‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(39,'‘S‚Ä‚ğ”j‰ó‚·‚é','‚·‚×‚Ä‚ğ‚Í‚©‚¢‚·‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(40,'¢ŠE‚ª•Ï‚í‚é','‚¹‚©‚¢‚ª‚©‚í‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(41,'¢ŠE‚ğª‚·‚é','‚¹‚©‚¢‚ğ‚¹‚¢‚·‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(42,'Û—‚ğ’´‚¦‚é','‚¹‚Â‚è‚ğ‚±‚¦‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(43,'U‚ß‘±‚¯‚é','‚¹‚ß‚Â‚Ã‚¯‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(44,'‘¶İ‚Ì‹–‚³‚ê‚È‚¢','‚»‚ñ‚´‚¢‚Ì‚ä‚é‚³‚ê‚È‚¢'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(45,'ŒŒ‚É‹Q‚¦‚µ','‚¿‚É‚¤‚¦‚µ'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(46,'’´','‚¿‚å‚¤'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(47,'’¼‹‚Å‚«‚È‚¢','‚¿‚å‚­‚µ‚Å‚«‚È‚¢'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(48,'‹­‚¢‹C‚ª‚·‚é','‚Â‚æ‚¢‚«‚ª‚·‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(49,'èŒ³‚É–ß‚é','‚Ä‚à‚Æ‚É‚à‚Ç‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(50,'“V‰º–³‘o‚Ì','‚Ä‚ñ‚©‚Ş‚»‚¤‚Ì'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(51,'“V‚É—^‚¦‚ç‚ê‚µ','‚Ä‚ñ‚É‚ ‚½‚¦‚ç‚ê‚µ'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(52,'“Š±—p‚Ì','‚Æ‚¤‚Ä‚«‚æ‚¤‚Ì'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(53,'‚Ç‚¤Œ©‚Ä‚à','‚Ç‚¤‚İ‚Ä‚à'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(54,'‰ğ‚«•ú‚Â','‚Æ‚«‚Í‚È‚Â'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(55,'“İŠí‚É‚È‚é','‚Ç‚ñ‚«‚É‚È‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(56,'ˆø‚«Œp‚ª‚ê‚é','‚Ğ‚«‚Â‚ª‚ê‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(57,'ˆø‚«Šñ‚¹‚é','‚Ğ‚«‚æ‚¹‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(58,'”é–§‚ğŒê‚é','‚Ğ‚İ‚Â‚ğ‚©‚½‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(59,'G‚ê‚Ä‚Í‚È‚ç‚È‚¢','‚Ó‚ê‚Ä‚Í‚È‚ç‚È‚¢'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(60,'‚×‚Á‚Æ‚è‚Æ•t‚¢‚½','‚×‚Á‚Æ‚è‚Æ‚Â‚¢‚½'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(61,'•‘‚¢~‚è‚½','‚Ü‚¢‚¨‚è‚½'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(62,'–¢—ˆ‚Ì‰^‚ğ‹z‚¤','‚İ‚ç‚¢‚Ì‚¤‚ñ‚ğ‚·‚¤'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(63,'‚à‚¤è•ú‚¹‚È‚¢','‚à‚¤‚Ä‚Î‚È‚¹‚È‚¢'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(64,'‹‚ß‘±‚¯‚½','‚à‚Æ‚ß‚Â‚Ã‚¯‚½'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(65,'Ä‚«s‚­‚·','‚â‚«‚Â‚­‚·'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(66,'–²‚Ì’†‚Åè‚É“ü‚ê‚µ','‚ä‚ß‚Ì‚È‚©‚Å‚Ä‚É‚¢‚ê‚µ'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(67,'–é‚ÉŒõ‚é','‚æ‚é‚É‚Ğ‚©‚é'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(68,'¢‚ğ“±‚­','‚æ‚ğ‚İ‚¿‚Ñ‚­'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(69,'—‰ğ‚Å‚«‚È‚¢','‚è‚©‚¢‚Å‚«‚È‚¢'); 
INSERT INTO m_super_rare(id, name, pronunciation) VALUES(70,'Ğ‚¢‚Ì’†S‚É‚ ‚é','‚í‚´‚í‚¢‚Ì‚¿‚ã‚¤‚µ‚ñ‚É‚ ‚é'); 
